### ISSUE TITLE
Web interface exception on yagi-feed ...

### ISSUE THREAD

**Issue by SandyWalsh** [MattDietz/yagi#17]
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/eventlet/wsgi.py", line 336, in handle_one_response
    result = self.application(self.environ, start_response)
  File "/usr/lib/pymodules/python2.6/webob/dec.py", line 147, in **call**
    resp = self.call_func(req, _args, *_self.kwargs)
  File "/usr/lib/pymodules/python2.6/webob/dec.py", line 208, in call_func
    return self.func(req, _args, *_kwargs)
  File "/usr/local/lib/python2.6/dist-packages/yagi-0.12-py2.6.egg/yagi/feed/feed.py", line 39, in route_request
    return self.get_all(req)
  File "/usr/local/lib/python2.6/dist-packages/yagi-0.12-py2.6.egg/yagi/feed/feed.py", line 66, in get_all
    elements = self.db_driver.get_all(self.pagesize, page)
TypeError: get_all() takes exactly 1 argument (3 given)

**Comment by SandyWalsh** [comment]
Also thrown ...

192.168.2.107 - - [18/Aug/2011 12:05:26] "GET / HTTP/1.1" 500 934 0.000895
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/eventlet/wsgi.py", line 336, in handle_one_response
    result = self.application(self.environ, start_response)
  File "/usr/lib/pymodules/python2.6/webob/dec.py", line 147, in **call**
    resp = self.call_func(req, _args, *_self.kwargs)
  File "/usr/lib/pymodules/python2.6/webob/dec.py", line 208, in call_func
    return self.func(req, _args, *_kwargs)
  File "/usr/local/lib/python2.6/dist-packages/yagi-0.12-py2.6.egg/yagi/feed/feed.py", line 38, in route_request
    return self.get_all_of_resource(req, resource)
  File "/usr/local/lib/python2.6/dist-packages/yagi-0.12-py2.6.egg/yagi/feed/feed.py", line 59, in get_all_of_resource
    page)
TypeError: get_all_of_type() takes exactly 2 arguments (4 given)

**Comment by SandyWalsh** [comment]
turns out redis is required now ... and the old devnul driver is bogus. Changed .conf accordingly and it works
