### ISSUE TITLE
Missing httplib2

### ISSUE THREAD

**Issue by antonym** [MattDietz/yagi#26]
Traceback (most recent call last):
  File "/usr/local/bin/yagi-event", line 5, in <module>
    pkg_resources.run_script('yagi==0.12', 'yagi-event')
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 467, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python2.6/dist-packages/pkg_resources.py", line 1200, in run_script
    execfile(script_filename, namespace, namespace)
  File "/usr/local/lib/python2.6/dist-packages/yagi-0.12-py2.6.egg/EGG-INFO/scripts/yagi-event", line 25, in <module>
    yagi.create_all_consumers()
  File "/usr/local/lib/python2.6/dist-packages/yagi-0.12-py2.6.egg/yagi/**init**.py", line 16, in create_all_consumers
    create_consumer(q)
  File "/usr/local/lib/python2.6/dist-packages/yagi-0.12-py2.6.egg/yagi/**init**.py", line 9, in create_consumer
    consumer = Consumer(queue_name, app, config)
  File "/usr/local/lib/python2.6/dist-packages/yagi-0.12-py2.6.egg/yagi/consumer.py", line 21, in **init**
    prev_app = yagi.utils.import_class(a)(prev_app)
  File "/usr/local/lib/python2.6/dist-packages/yagi-0.12-py2.6.egg/yagi/utils.py", line 13, in import_class
    raise Exception("Could not load class %s" % klass_str)
Exception: Could not load class yagi.handler.atompub_handler.AtomPub

**Comment by antonym** [comment]
https://github.com/Cerberus98/yagi/pull/27
