### ISSUE TITLE
'NoneType' object has no attribute 'method_writer'

### ISSUE THREAD

**Issue by antonym** [MattDietz/yagi#38]
[ERROR at 2012-02-01 00:16:51,612 line: 169] 'NoneType' object has no attribute 'method_writer'
Traceback (most recent call last):
  File "/usr/lib/pymodules/python2.6/yagi/broker/rabbit.py", line 150, in loop
    msg = consumer.consumer.fetch(enable_callbacks=False)
  File "/usr/lib/pymodules/python2.6/carrot/messaging.py", line 303, in fetch
    message = self.backend.get(self.queue, no_ack=no_ack)
  File "/usr/lib/pymodules/python2.6/carrot/backends/pyamqplib.py", line 264, in get
    raw_message = self.channel.basic_get(queue, no_ack=no_ack)
  File "/usr/lib/pymodules/python2.6/amqplib/client_0_8/channel.py", line 2029, in basic_get
    self._send_method((60, 70), args)
  File "/usr/lib/pymodules/python2.6/amqplib/client_0_8/abstract_channel.py", line 69, in _send_method
    self.connection.method_writer.write_method(self.channel_id,
AttributeError: 'NoneType' object has no attribute 'method_writer'
[ERROR at 2012-02-01 00:16:51,612 line: 169] 'NoneType' object has no attribute 'method_writer'

**Comment by antonym** [comment]
Still getting this... seems that if Rabbit connectivity is lost, it will spin this error over and over again.
